### ISSUE TITLE
Playwright Report In Excel

### ISSUE THREAD

**Issue by srujithapyla** [vivifyhealthcare/Playwright_API_Testing#3]
**About Playwright_Excel:**

Excel Report for the API Testing via Playwright has been devised to represnt the data in the analytical form and and make it readily available for the asessment. Report in excel is easily understandable and highly customizable. 
We are summarizing Data in excel for the set of API endpoints with the set of test cases executed having structutred like this Sample View shown below

![image](https://user-images.githubusercontent.com/92718918/229702006-88400e85-2dc1-4055-986b-5058f600e6d0.png)

Primarily, This customized report is prepaired to analyze endpoints working status, i.e. 200.

The report typically contains detailed information about the API and it's Sections; such as the name of the API, Status, Status code, API Type, Section Name, Date & Time of Execution, and the Environment Name. All these headers can be customized as per the usability and expected output for the visibility of the Report.

**Comment by neelidevikanjali** [comment]
Excel Report for the API Testing via Playwright has been devised to represnt the data in the analytical form and and make it readily available for the assessment. Report in excel is easily understandable and highly customizable.

![image](https://user-images.githubusercontent.com/109802337/230077241-23e7e150-ae01-4393-b4ad-79d515ca9954.png)
