### ISSUE TITLE
Multiple TestCases for Multiple Projects/Products

### ISSUE THREAD

**Issue by sacredabhishek** [vivifyhealthcare/Playwright_API_Testing#6]
**Problem Statement**
Testing Setup at one place for  API Endpoints related to multiple Products/ Projects (Grouping)

**Solution**
Reshaped the Testing Code Block for Grouping the Endpoints with Product/Project and Save the Test Cases and their respective outcomes in to different collections. for example:

1. Product A - Lifeeazy 
   i. API Collections Mapped in a Group 
   ii. Test Cases uploaded via API
   iii. Test Case saved in MongoDB Collection for Lifeeazy 
   iv. Test Case Execution and Saved Data for the processed / executed test cases in MongoDB  
3. Product B - IVINPro
   i. API Collections Mapped in a Group 
   ii. Test Cases uploaded via API
   iii. Test Case saved in MongoDB Collection for IVINPro
   iv. Test Case Execution and Saved Data for the processed / executed test cases in MongoDB  

**Additional context**
on execution of the testing; by default - test cases will be executed for both the Products, however it can be switched to specific by commenting the grouped API set.

**Comment by neelidevikanjali** [comment]
https://github.com/orgs/vivifyhealthcare/discussions/41
